# Generated by Django 5.2.1 on 2025-05-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('employee', 'Empleado')], default='employee', max_length=10),
        ),
    ]
