# Generated by Django 5.2.1 on 2025-05-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
    ]
