# Generated by Django 5.2.1 on 2025-05-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0002_remove_event_description_remove_event_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
