# Generated by Django 5.2.1 on 2025-06-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0003_event_is_template_alter_event_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_template',
        ),
    ]
