# Generated by Django 5.2.1 on 2025-06-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0004_remove_event_is_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='all_day',
        ),
    ]
