# Generated by Django 5.2 on 2025-08-07 19:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ventas', 'Reporte de Ventas'), ('stock', 'Reporte de Stock')], max_length=20, verbose_name='Tipo de reporte')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10, verbose_name='Formato')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('ruta_archivo', models.CharField(max_length=500, verbose_name='Ruta del archivo')),
                ('tamaño_archivo', models.BigIntegerField(default=0, verbose_name='Tamaño del archivo')),
                ('estado', models.CharField(choices=[('pendiente', 'En proceso'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('total_registros', models.IntegerField(default=0, verbose_name='Total registros')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto total')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
