# Generated by Django 5.2.1 on 2025-07-31 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('ruta_archivo', models.CharField(max_length=500, verbose_name='Ruta del archivo')),
                ('tamaño_archivo', models.BigIntegerField(default=0, verbose_name='Tamaño del archivo')),
                ('estado', models.CharField(choices=[('pendiente', 'En proceso'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('total_productos', models.IntegerField(default=0, verbose_name='Total productos respaldados')),
                ('total_categorias', models.IntegerField(default=0, verbose_name='Total categorías respaldadas')),
                ('total_usuarios', models.IntegerField(default=0, verbose_name='Total usuarios respaldados')),
                ('total_ventas', models.IntegerField(default=0, verbose_name='Total ventas respaldadas')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
